import{a as B,S as $,i as l}from"./assets/vendor-DvfmeZXB.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();async function b(e,n=1){const r="53391690-3e647f595737bbf778d07baf8",s="https://pixabay.com/api/";try{return(await B.get(s,{params:{key:r,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:n}})).data}catch(t){throw t}}const f=document.querySelector(".gallery"),a=document.querySelector(".loader"),g=document.querySelector(".load-more"),E=new $(".gallery a",{captionsData:"alt",captionDelay:250});function x(e){return e?String(e).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"):""}function S(e){if(!f||!Array.isArray(e))return;const n=e.map(r=>{const{webformatURL:s,largeImageURL:t,tags:o,likes:i,views:m,comments:u,downloads:p}=r;return`
      <li class="gallery-item">
        <a class="gallery-link" href="${t}">
          <img class="gallery-image" src="${s}" alt="${x(o)}" loading="lazy" />
        </a>
        <div class="info">
          <p><strong>Likes:</strong> ${i}</p>
          <p><strong>Views:</strong> ${m}</p>
          <p><strong>Comments:</strong> ${u}</p>
          <p><strong>Downloads:</strong> ${p}</p>
        </div>
      </li>`}).join("");f.insertAdjacentHTML("beforeend",n),E.refresh()}function O(){if(f){f.innerHTML="";try{E.refresh()}catch{}}}function q(){a&&(a.classList.remove("is-hidden"),a.classList.add("visible"))}function L(){a&&(a.classList.add("is-hidden"),a.classList.remove("visible"))}function C(){g&&g.classList.remove("is-hidden")}function w(){g&&g.classList.add("is-hidden")}const M={galleryContainer:f,loadMoreBtn:g,loaderEl:a},D=document.querySelector(".form"),v=M.loadMoreBtn,P=M.galleryContainer;let h="",c=1,A=0;const R=15;let d=!1;D.addEventListener("submit",H);v&&v.addEventListener("click",I);async function H(e){if(e.preventDefault(),h=e.target.elements["search-text"].value.trim(),!h){l.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}c=1,O(),w(),q();try{d=!0;const r=await b(h,c);if(!r||!Array.isArray(r.hits)||r.hits.length===0){L(),l.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}S(r.hits),A=Math.ceil((r.totalHits||0)/R),c<A?C():w()}catch(r){console.error(r),l.error({title:"Error",message:"Something went wrong while fetching images.",position:"topRight"})}finally{L(),d=!1}}async function I(){if(!d){c+=1,q();try{d=!0;const e=await b(h,c);if(!e||!Array.isArray(e.hits)){l.error({title:"Error",message:"Unexpected response from server",position:"topRight"});return}S(e.hits),await T(P),_(),c>=Math.ceil((e.totalHits||0)/R)&&(w(),l.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){console.error(e),l.error({title:"Error",message:"Something went wrong while loading more images.",position:"topRight"})}finally{L(),d=!1}}}function T(e,n=5e3){const r=Array.from(e.querySelectorAll("img"));return r.length===0?Promise.resolve():new Promise(s=>{let t=0;const o=r.length;let i=!1;const m=()=>{i||(i=!0,clearTimeout(p),s())},u=()=>{t+=1,t>=o&&m()};r.forEach(y=>{y.complete?u():(y.addEventListener("load",u,{once:!0}),y.addEventListener("error",u,{once:!0}))});const p=setTimeout(()=>{m()},n)})}function _(){const e=P.querySelector(".gallery-item");if(!e)return;const{height:n}=e.getBoundingClientRect();window.scrollBy({top:n*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
