import{a as _,S as A,i as f}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function y(t,o=1){const s="53391690-3e647f595737bbf778d07baf8",n="https://pixabay.com/api/",e={key:s,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};try{return(await _.get(n,{params:e})).data}catch(r){throw r}}const l=document.querySelector(".gallery"),c=document.querySelector(".loader"),u=document.querySelector(".load-more"),p=new A(".gallery a",{captionsData:"alt",captionDelay:250});function M(t){return t?String(t).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"):""}function g(t){if(!l||!Array.isArray(t))return;const o=t.map(s=>{const{webformatURL:n,largeImageURL:e,tags:r,likes:i,views:w,comments:v,downloads:S}=s;return`
      <li class="gallery__item">
        <a class="gallery__link" href="${e}">
          <img class="gallery__image" src="${n}" alt="${M(r)}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${i}</p>
          <p><b>Views:</b> ${w}</p>
          <p><b>Comments:</b> ${v}</p>
          <p><b>Downloads:</b> ${S}</p>
        </div>
      </li>`}).join("");l.insertAdjacentHTML("beforeend",o),p.refresh()}function q(){if(l){l.innerHTML="";try{p.refresh()}catch{}}}function h(){c&&c.classList.add("visible")}function b(){c&&c.classList.remove("visible")}function B(){u&&u.classList.remove("is-hidden")}function L(){u&&u.classList.add("is-hidden")}const P={galleryContainer:l,loaderEl:c,loadMoreBtn:u},$=document.querySelector(".form"),E=P.loadMoreBtn;let d="",a=1,m=0;$.addEventListener("submit",O);E.addEventListener("click",x);async function O(t){if(t.preventDefault(),d=t.target.elements["search-text"].value.trim(),!!d){a=1,q(),L(),h();try{const o=await y(d,a);if(!o.hits.length){f.error({message:"Sorry, there are no images matching your search query."});return}g(o.hits),m=Math.ceil(o.totalHits/15),a<m&&B()}catch{f.error({message:"Something went wrong. Please try again."})}finally{b()}}}async function x(){a+=1,h();try{const t=await y(d,a);g(t.hits),D(),a>=m&&(L(),f.info({message:"We're sorry, but you've reached the end of search results."}))}catch{f.error({message:"Something went wrong. Please try again."})}finally{b()}}function D(){const t=document.querySelector(".gallery__item");if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
