import{a as M,S as B,i as d}from"./assets/vendor-DvfmeZXB.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function y(t,o=1){const s="53391690-3e647f595737bbf778d07baf8",a="https://pixabay.com/api/";try{return(await M.get(a,{params:{key:s,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}})).data}catch(e){throw e}}const c=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),h=new B(".gallery a",{captionsData:"alt",captionDelay:250});function g(t){if(!c||!Array.isArray(t))return;const o=t.map(s=>{const{webformatURL:a,largeImageURL:e,tags:r,likes:i,views:v,comments:S,downloads:q}=s;return`
      <li class="gallery-item">
        <a class="gallery-link" href="${e}">
          <img class="gallery-image" src="${a}" alt="${r}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${i}</p>
          <p><b>Views:</b> ${v}</p>
          <p><b>Comments:</b> ${S}</p>
          <p><b>Downloads:</b> ${q}</p>
        </div>
      </li>`}).join("");c.insertAdjacentHTML("beforeend",o),h.refresh()}function E(){c&&(c.innerHTML="",h.refresh())}function p(){f.classList.remove("is-hidden")}function L(){f.classList.add("is-hidden")}function $(){m.classList.remove("is-hidden")}function b(){m.classList.add("is-hidden")}const w={galleryContainer:c,loadMoreBtn:m,loaderEl:f};let l="",n=1,u=0;w.loadMoreBtn.addEventListener("click",O);document.querySelector(".form").addEventListener("submit",A);async function A(t){if(t.preventDefault(),l=t.target.elements["search-text"].value.trim(),!!l){n=1,E(),b(),p();try{const s=await y(l,n);if(!s.hits.length){d.error({message:"No images found for your query."});return}g(s.hits),u=Math.ceil(s.totalHits/15),n<u&&$()}catch{d.error({message:"Error fetching images."})}finally{L()}}}async function O(){n+=1,p();try{const t=await y(l,n);g(t.hits),P(),n>=u&&(b(),d.info({message:"We're sorry, but you've reached the end of search results."}))}catch{d.error({message:"Error fetching images."})}finally{L()}}function P(){var o;const t=((o=w.galleryContainer.querySelector(".gallery__item"))==null?void 0:o.getBoundingClientRect().height)||0;window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
